---
title: "Prediction for shiny"
author: "Xi Fang"
date: "8/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data
```{r data}
bf   <- "en_US.blogs.txt"
nf    <- "en_US.news.txt"
tf    <- "en_US.twitter.txt"  
b <- readLines(bf, skipNul = TRUE)
n <- readLines(nf, skipNul = TRUE)
t <- readLines(tf, skipNul = TRUE)

## create dataframe
b <- data.frame(text=b)
n <- data.frame(text=n)
t <- data.frame(text=t)

```

## Random sampling
```{r sample}
set.seed(2020)
library(dplyr)
bs <- b %>%
        sample_n(.,nrow(b)*0.1)
ns <- n %>%
        sample_n(.,nrow(n)*0.1)
ts <- t %>%
        sample_n(.,nrow(t)*0.1)

## combine and create tidy sample data
t_sample <- bind_rows(mutate(bs, source="blogs"),
                      mutate(ns, source="news"),
                      mutate(ts, source="twitter"))
t_sample$source <- as.factor(t_sample$source)
rm(list = c("b", "bf", "bs","n", "nf",     
            "ns", "t","tf", 
            "ts"))

```

## Clean the sample data
```{r clean}
replace_reg <- "[^[:alpha:][:space:]]*" # create filters for non-alphanumeric’s
replace_url <- "http[^[:space:]]*" # create filters for url's
replace_aaa <- "\\b(?=\\w*(\\w)\\1)\\w+\\b"  # create filters for letters repeated over three times

## create clean samples based on tidy samples
library("stringr")
library(dplyr)
c_sample <- t_sample %>%
        mutate(text = str_replace_all(text, replace_reg, "")) %>%
        mutate(text = str_replace_all(text, replace_url, "")) %>%
        mutate(text = str_replace_all(text, replace_aaa, "")) %>% 
        mutate(text = iconv(text, "ASCII//TRANSLIT"))

rm(list = c("t_sample"))
```


## Create n-grams
```{r ngram}
library(tidytext)
bigram_rp <- c_sample  %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2, collapse = FALSE)

trigram_rp <- c_sample  %>%
  unnest_tokens(trigram, text, token = "ngrams", n = 3, collapse = FALSE)
sum(is.na(trigram_rp)) # check how many NAs

quadgram_rp <- c_sample  %>%
  unnest_tokens(quadgram, text, token = "ngrams", n = 4, collapse = FALSE)

quintgram_rp <- c_sample  %>%
  unnest_tokens(quintgram, text, token = "ngrams", n = 5, collapse = FALSE)

```

## Reduce the n-gram dataset

```{r reduce}
bigram_c <- bigram_rp %>%
        count(bigram) %>%
        filter(n>10) %>%
        arrange(desc(n))
rm(list = c("bigram_rp"))

trigram_c <- trigram_rp %>%
        count(trigram) %>%
        filter(n>10) %>%
        arrange(desc(n))
#rm(list = c("trigram_rp"))

quadgram_c <- quadgram_rp %>%
        count(quadgram) %>%
        filter(n>10) %>%
        arrange(desc(n))
rm(list = c("quadgram_rp"))

quintgram_c <- quintgram_rp %>%
        count(quintgram) %>%
        filter(n>10) %>%
        arrange(desc(n))
rm(list = c("quintgram_rp"))
```

## ngram figures
```{r plots}
bigram_c %>%
  top_n(20, n) %>%
  mutate(bigram = reorder(bigram, n)) %>%
  ggplot(aes(bigram, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Bigrams")
ggsave("bigram.png")

trigram_c %>%
  top_n(20, n) %>%
  mutate(trigram = reorder(trigram, n)) %>%
  ggplot(aes(trigram, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Trigrams")
ggsave("trigram.png")


quadgram_c %>%
  top_n(20, n) %>%
  mutate(quadgram = reorder(quadgram, n)) %>%
  ggplot(aes(quadgram, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Quadgrams")
ggsave("quadgram.png")

quintgram_c %>%
  top_n(20, n) %>%
  mutate(quintgram = reorder(quintgram, n)) %>%
  ggplot(aes(quintgram, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Quintgrams")
ggsave("quintgram.png")

```

## Separate the words in n-gram dataset
```{r separate}
library(tidyr)
bigram_w <- bigram_c %>%
  separate(bigram, c("word1", "word2"), sep = " ")
bigram_w

trigram_w <- trigram_c %>%
  separate(trigram, c("word1", "word2","word3"), sep = " ")
trigram_w

quadgram_w <- quadgram_c %>%
  separate(quadgram, c("word1", "word2","word3", "word4"), sep = " ")
quadgram_w

quintgram_w <- quintgram_c %>%
  separate(quintgram, c("word1", "word2","word3","word4","word5"), sep = " ")
quintgram_w

## Save these files for shiny
saveRDS(bigram_w, "bigram_w.rds")
saveRDS(trigram_w, "trigram_w.rds")
saveRDS(quadgram_w,"quadgram_w.rds")
saveRDS(quintgram_w,"quintgram_w.rds")

```


## Setup prediction model
```{r setup}
go <- Sys.time()
library(tidyverse)
library(stringr)

bigram_w <- readRDS("bigram_w.rds")
trigram_w <- readRDS("trigram_w.rds")
quadigram_w <- readRDS("quadgram_w.rds")
quintigram_w <- readRDS("quintgram_w.rds")

```

## Create prediction model
```{r predict}
bigram <- function(input_words){
                    num <- length(input_words)
                    filter(bigram_w, 
                          word1==input_words[num]) %>% 
                    top_n(1, n) %>%
                    filter(row_number() == 1L) %>%
                    select(num_range("word", 2)) %>%
                    as.character() -> out
                    ifelse(out =="character(0)", "?", return(out))
}


trigram <- function(input_words){
                    num <- length(input_words)
                    filter(trigram_w, 
                            word1==input_words[num-1], 
                            word2==input_words[num])  %>% 
                    top_n(1, n) %>%
                    filter(row_number() == 1L) %>%
                    select(num_range("word", 3)) %>%
                    as.character() -> out
                    ifelse(out=="character(0)", bigram(input_words), return(out))
}


quadgram <- function(input_words){
                    num <- length(input_words)
                    filter(quadgram_w, 
                            word1==input_words[num-2], 
                            word2==input_words[num-1], 
                            word3==input_words[num])  %>% 
                    top_n(1, n) %>%
                    filter(row_number() == 1L) %>%
                    select(num_range("word", 4)) %>%
                    as.character() -> out
                    ifelse(out=="character(0)", trigram(input_words), return(out))
}

```


##  User input
```{r user}
ngrams <- function(input){
  # Create a dataframe
  input <- data_frame(text = input)
  # Clean the Inpput
  replace_reg <- "[^[:alpha:][:space:]]*"
  input <- input %>%
    mutate(text = str_replace_all(text, replace_reg, ""))
  # Find word count, separate words, lower case
  input_count <- str_count(input, boundary("word"))
  input_words <- unlist(str_split(input, boundary("word")))
  input_words <- tolower(input_words)
  # Call the matching functions
  out <- ifelse(input_count == 1, bigram(input_words), 
              ifelse (input_count == 2, trigram(input_words), quadgram(input_words)))
  # Output
  return(out)
}

input <- "In case of a"
ngrams(input)

## Give back the time
stop <- Sys.time()
(how_long <- stop - go)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
